### PR TITLE
feat: remove conda-store environment

### PR DESCRIPTION
**Pull request by gabalafou**
Per [conda-store API docs](https://conda-store.readthedocs.io/en/latest/contributing.html#rest-api).

Note: this PR is against conda-store-integration branch, not the main branch.

### CODE REVIEW

**Comment by gabalafou** [comment]
@pierrotsmnrd I forgot if I'm supposed to create a pull request against our repo or mamba-org's

**Comment by gabalafou** [comment]
I tested this locally, running conda-store in a Docker container and running JupyterLab locally. I created a new environment in the UI, then subsequently deleted it and verified that it disappeared both from the JupyterLab UI and from the conda-store web API at localhost:5000

**Comment by pierrotsmnrd** [comment]
Hi @gabalafou  :) 
The PRs are meant to be made against the `conda-store-integration` branch on the upstream repo : https://github.com/mamba-org/gator/tree/conda-store-integration
I let you close this PR and open a new one, if that's ok for you ? :) 
Thanks a lot

**Comment by gabalafou** [comment]
Move to https://github.com/mamba-org/gator/pull/173

**Pull request closed without merging**
